language: python
python:
- '3.5'
- '3.6'
cache: pip
install:
- pip install -U pip
- pip install -r requirements.txt
script:
- python -m doctest ecies/utils.py
- python -m unittest discover .
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kigawas
  password:
    secure: cdWBxLs5nzKv4y1FCupwS8hKONe0q1+QvcC4OgdftVw7Kf2YYwRJJhyMipr31IQf3n2JVK1G9N8r20D1XbNXZpqHpzp5sCi+CWFHVCWBax2RQnxujfrT1lVT9EZBgHoyqaJ5S6WPoai8+KiA3F6+6qcihU4qcHXEkptgbHB38G6OFMZIZh7YFnh3nVs+H4FD8ec3d4vmedp1caK/zYqoBenx//0xZJjDdbEa4ZFo7I1+uUiVritgSz1wPd2hhav2Ifcg1cZrFmrqfAzeXGk1guSCQlyuCTze3gLmvYclDLdULZbu6MCmp5ZzexPG0DKJQeV/sP26EHvJA3+81/odey/RlS/ayYHLgCFmGYP2PNsjFdFJdelZ/GgTHnCoRSN0Y31PJe3fS30n/NXwKU8olKs1kD4SGklwa71ZpfGhnu+J0q3W7naTailk704CLV9w+JoJlzOPWeyhNjJzAu7XxsGltfwjyASCp44bj3qYc/Z6S0mwaCGJsJ84WYSE8EwEteBjjHLr7HkFrpuz0fu40WL1S17p7t8LZyryUCdNW1hHfS8717WxU44Wk2p102h4CvhZtmB4yA9tbeC4l2nEsZlTWfq+lYdup57jtPpojcPYgB2ARW12iuH2Mpw6Jb5LdTWGA89hjeKXtQ015wvdUTGSEacEyfA0umZZuGvD6mc=
  on:
    tags: true
