version: 2.1
jobs:
  test-38: &test-template
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            . $HOME/.poetry/env
            poetry install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pip install codecov codacy-coverage
            coverage run -m doctest -v ecies/utils.py
            coverage run -m unittest discover .
            codecov
            python-codacy-coverage -r coverage.xml
  test-37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Setup env
          command: |
            python3 -m venv venv
            venv/bin/pip install -U pip twine wheel
            venv/bin/python setup.py install

      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            python setup.py verify
            python setup.py sdist bdist_wheel
            twine upload dist/* --repository-url https://test.pypi.org/legacy/
            twine upload dist/*

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-38:
          filters:
            tags:
              only: /^v.*/
      - test-37:
          filters:
            tags:
              only: /^v.*/
      - test-36:
          filters:
            tags:
              only: /^v.*/
      - test-35:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test-38
            - test-37
            - test-36
            - test-35
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
